# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_cadastroAdm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadastroAdm(object):
    def setupUi(self, CadastroAdm):
        CadastroAdm.setObjectName("CadastroAdm")
        CadastroAdm.resize(443, 691)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CadastroAdm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(CadastroAdm)
        self.frame.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bt_salvarloginAdm = QtWidgets.QPushButton(self.frame)
        self.bt_salvarloginAdm.setEnabled(True)
        self.bt_salvarloginAdm.setGeometry(QtCore.QRect(100, 580, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_salvarloginAdm.setFont(font)
        self.bt_salvarloginAdm.setStyleSheet("QPushButton{\n"
"    background-color: rgba(221, 33, 33, 0.99);\n"
"    border-radius: 12px;\n"
"    color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 206, 137);\n"
"    border-radius: 12px;\n"
"    color: rgb(100, 76, 47);\n"
"}\n"
"")
        self.bt_salvarloginAdm.setObjectName("bt_salvarloginAdm")
        self.tck = QtWidgets.QLabel(self.frame)
        self.tck.setGeometry(QtCore.QRect(20, 10, 51, 31))
        self.tck.setStyleSheet("")
        self.tck.setText("")
        self.tck.setPixmap(QtGui.QPixmap("../imgs/tickets.png"))
        self.tck.setScaledContents(True)
        self.tck.setObjectName("tck")
        self.texto_infoAdm = QtWidgets.QTextEdit(self.frame)
        self.texto_infoAdm.setGeometry(QtCore.QRect(20, 70, 411, 31))
        self.texto_infoAdm.setStyleSheet("border: none;")
        self.texto_infoAdm.setObjectName("texto_infoAdm")
        self.texto_erro2 = QtWidgets.QTextEdit(self.frame)
        self.texto_erro2.setGeometry(QtCore.QRect(70, 530, 291, 31))
        self.texto_erro2.setStyleSheet("border: none;")
        self.texto_erro2.setObjectName("texto_erro2")
        self.box_insertUsuario = QtWidgets.QLineEdit(self.frame)
        self.box_insertUsuario.setGeometry(QtCore.QRect(20, 130, 371, 31))
        self.box_insertUsuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"border: none;")
        self.box_insertUsuario.setObjectName("box_insertUsuario")
        self.texto_usuarioAdm = QtWidgets.QTextEdit(self.frame)
        self.texto_usuarioAdm.setGeometry(QtCore.QRect(20, 100, 151, 31))
        self.texto_usuarioAdm.setStyleSheet("border: none;")
        self.texto_usuarioAdm.setObjectName("texto_usuarioAdm")
        self.texto_senhaAdm = QtWidgets.QTextEdit(self.frame)
        self.texto_senhaAdm.setGeometry(QtCore.QRect(20, 340, 104, 31))
        self.texto_senhaAdm.setStyleSheet("border: none;")
        self.texto_senhaAdm.setObjectName("texto_senhaAdm")
        self.texto_topo = QtWidgets.QTextEdit(self.frame)
        self.texto_topo.setGeometry(QtCore.QRect(90, 10, 151, 41))
        self.texto_topo.setStyleSheet("border: none;\n"
"color: rgba(221, 33, 33, 0.99);")
        self.texto_topo.setObjectName("texto_topo")
        self.box_insertEmail = QtWidgets.QLineEdit(self.frame)
        self.box_insertEmail.setGeometry(QtCore.QRect(20, 200, 371, 31))
        self.box_insertEmail.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"border: none;")
        self.box_insertEmail.setObjectName("box_insertEmail")
        self.box_insertTelefone = QtWidgets.QLineEdit(self.frame)
        self.box_insertTelefone.setGeometry(QtCore.QRect(20, 280, 371, 31))
        self.box_insertTelefone.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"border: none;")
        self.box_insertTelefone.setObjectName("box_insertTelefone")
        self.box_insertSenha = QtWidgets.QLineEdit(self.frame)
        self.box_insertSenha.setGeometry(QtCore.QRect(20, 370, 371, 31))
        self.box_insertSenha.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"border: none;")
        self.box_insertSenha.setObjectName("box_insertSenha")
        self.texto_emailAdm = QtWidgets.QTextEdit(self.frame)
        self.texto_emailAdm.setGeometry(QtCore.QRect(20, 170, 151, 31))
        self.texto_emailAdm.setStyleSheet("border: none;")
        self.texto_emailAdm.setObjectName("texto_emailAdm")
        self.texto_confirmaSenhaAdm = QtWidgets.QTextEdit(self.frame)
        self.texto_confirmaSenhaAdm.setGeometry(QtCore.QRect(20, 430, 201, 31))
        self.texto_confirmaSenhaAdm.setStyleSheet("border: none;")
        self.texto_confirmaSenhaAdm.setObjectName("texto_confirmaSenhaAdm")
        self.texto_telefoneAdm = QtWidgets.QTextEdit(self.frame)
        self.texto_telefoneAdm.setGeometry(QtCore.QRect(20, 250, 104, 31))
        self.texto_telefoneAdm.setStyleSheet("border: none;")
        self.texto_telefoneAdm.setObjectName("texto_telefoneAdm")
        self.box_confirmaSenha = QtWidgets.QLineEdit(self.frame)
        self.box_confirmaSenha.setGeometry(QtCore.QRect(20, 460, 371, 31))
        self.box_confirmaSenha.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"border: none;")
        self.box_confirmaSenha.setObjectName("box_confirmaSenha")
        self.bt_voltar = QtWidgets.QPushButton(self.frame)
        self.bt_voltar.setEnabled(True)
        self.bt_voltar.setGeometry(QtCore.QRect(380, 630, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_voltar.setFont(font)
        self.bt_voltar.setStyleSheet("QPushButton{\n"
"    background-color: rgba(221, 33, 33, 0.99);\n"
"    border-radius: 12px;\n"
"    color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 206, 137);\n"
"    border-radius: 12px;\n"
"    color: rgb(100, 76, 47);\n"
"}\n"
"")
        self.bt_voltar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../imgs/voltar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_voltar.setIcon(icon)
        self.bt_voltar.setIconSize(QtCore.QSize(25, 25))
        self.bt_voltar.setObjectName("bt_voltar")
        self.texto_infoAdm.raise_()
        self.texto_emailAdm.raise_()
        self.texto_senhaAdm.raise_()
        self.texto_usuarioAdm.raise_()
        self.texto_erro2.raise_()
        self.tck.raise_()
        self.bt_salvarloginAdm.raise_()
        self.box_insertUsuario.raise_()
        self.texto_topo.raise_()
        self.box_insertEmail.raise_()
        self.box_insertTelefone.raise_()
        self.box_insertSenha.raise_()
        self.texto_confirmaSenhaAdm.raise_()
        self.texto_telefoneAdm.raise_()
        self.box_confirmaSenha.raise_()
        self.bt_voltar.raise_()
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(CadastroAdm)
        QtCore.QMetaObject.connectSlotsByName(CadastroAdm)

    def retranslateUi(self, CadastroAdm):
        _translate = QtCore.QCoreApplication.translate
        CadastroAdm.setWindowTitle(_translate("CadastroAdm", "Cadastro ADM"))
        self.bt_salvarloginAdm.setText(_translate("CadastroAdm", "SALVAR"))
        self.texto_infoAdm.setHtml(_translate("CadastroAdm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Preencha os campos abaixo para realizar seu cadastro.</span></p></body></html>"))
        self.texto_erro2.setHtml(_translate("CadastroAdm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.texto_usuarioAdm.setHtml(_translate("CadastroAdm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Nome de usuário</span></p></body></html>"))
        self.texto_senhaAdm.setHtml(_translate("CadastroAdm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Senha</span></p></body></html>"))
        self.texto_topo.setHtml(_translate("CadastroAdm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Bilheteria Online</span></p></body></html>"))
        self.texto_emailAdm.setHtml(_translate("CadastroAdm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">E-mail</span></p></body></html>"))
        self.texto_confirmaSenhaAdm.setHtml(_translate("CadastroAdm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Confirmação de senha</span></p></body></html>"))
        self.texto_telefoneAdm.setHtml(_translate("CadastroAdm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Telefone</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CadastroAdm = QtWidgets.QWidget()
    ui = Ui_CadastroAdm()
    ui.setupUi(CadastroAdm)
    CadastroAdm.show()
    sys.exit(app.exec_())
