# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_loginAdm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginAdm(object):
    def setupUi(self, LoginAdm):
        LoginAdm.setObjectName("LoginAdm")
        LoginAdm.resize(443, 693)
        self.frame = QtWidgets.QFrame(LoginAdm)
        self.frame.setGeometry(QtCore.QRect(10, 10, 421, 671))
        self.frame.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bt_cadastrarAdm = QtWidgets.QPushButton(self.frame)
        self.bt_cadastrarAdm.setGeometry(QtCore.QRect(230, 540, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_cadastrarAdm.setFont(font)
        self.bt_cadastrarAdm.setStyleSheet("QPushButton{\n"
"    background-color: rgba(221, 33, 33, 0.99);\n"
"    border-radius: 12px;\n"
"    color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 206, 137);\n"
"    border-radius: 12px;\n"
"    color: rgb(100, 76, 47);\n"
"}")
        self.bt_cadastrarAdm.setObjectName("bt_cadastrarAdm")
        self.bt_loginAdm = QtWidgets.QPushButton(self.frame)
        self.bt_loginAdm.setEnabled(True)
        self.bt_loginAdm.setGeometry(QtCore.QRect(110, 400, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_loginAdm.setFont(font)
        self.bt_loginAdm.setStyleSheet("QPushButton{\n"
"    background-color: rgba(221, 33, 33, 0.99);\n"
"    border-radius: 12px;\n"
"    color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 206, 137);\n"
"    border-radius: 12px;\n"
"    color: rgb(100, 76, 47);\n"
"}\n"
"")
        self.bt_loginAdm.setObjectName("bt_loginAdm")
        self.tck = QtWidgets.QLabel(self.frame)
        self.tck.setGeometry(QtCore.QRect(160, 30, 111, 71))
        self.tck.setStyleSheet("")
        self.tck.setText("")
        self.tck.setPixmap(QtGui.QPixmap("../imgs/tickets.png"))
        self.tck.setScaledContents(True)
        self.tck.setObjectName("tck")
        self.texto_bemvindo = QtWidgets.QTextEdit(self.frame)
        self.texto_bemvindo.setGeometry(QtCore.QRect(50, 130, 351, 41))
        self.texto_bemvindo.setStyleSheet("border: none;")
        self.texto_bemvindo.setObjectName("texto_bemvindo")
        self.box_senha = QtWidgets.QLineEdit(self.frame)
        self.box_senha.setGeometry(QtCore.QRect(100, 300, 241, 31))
        self.box_senha.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"border: none;")
        self.box_senha.setObjectName("box_senha")
        self.texto_ask = QtWidgets.QTextEdit(self.frame)
        self.texto_ask.setGeometry(QtCore.QRect(50, 540, 211, 41))
        self.texto_ask.setStyleSheet("border: none;")
        self.texto_ask.setObjectName("texto_ask")
        self.texto_erro = QtWidgets.QTextEdit(self.frame)
        self.texto_erro.setGeometry(QtCore.QRect(103, 350, 231, 31))
        self.texto_erro.setStyleSheet("border: none;")
        self.texto_erro.setObjectName("texto_erro")
        self.box_usuario = QtWidgets.QLineEdit(self.frame)
        self.box_usuario.setGeometry(QtCore.QRect(100, 230, 241, 31))
        self.box_usuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"border: none;")
        self.box_usuario.setObjectName("box_usuario")
        self.texto_usuario = QtWidgets.QTextEdit(self.frame)
        self.texto_usuario.setGeometry(QtCore.QRect(100, 200, 104, 31))
        self.texto_usuario.setStyleSheet("border: none;")
        self.texto_usuario.setObjectName("texto_usuario")
        self.texto_senha = QtWidgets.QTextEdit(self.frame)
        self.texto_senha.setGeometry(QtCore.QRect(100, 270, 104, 31))
        self.texto_senha.setStyleSheet("border: none;")
        self.texto_senha.setObjectName("texto_senha")
        self.texto_senha.raise_()
        self.texto_usuario.raise_()
        self.texto_ask.raise_()
        self.bt_cadastrarAdm.raise_()
        self.tck.raise_()
        self.bt_loginAdm.raise_()
        self.texto_bemvindo.raise_()
        self.box_senha.raise_()
        self.texto_erro.raise_()
        self.box_usuario.raise_()

        self.retranslateUi(LoginAdm)
        QtCore.QMetaObject.connectSlotsByName(LoginAdm)

    def retranslateUi(self, LoginAdm):
        _translate = QtCore.QCoreApplication.translate
        LoginAdm.setWindowTitle(_translate("LoginAdm", "Login ADM"))
        self.bt_cadastrarAdm.setText(_translate("LoginAdm", "FAZER CADASTRO"))
        self.bt_loginAdm.setText(_translate("LoginAdm", "LOGIN"))
        self.texto_bemvindo.setHtml(_translate("LoginAdm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Bem-Vindo ao Login do Adminstrador!</span></p></body></html>"))
        self.texto_ask.setHtml(_translate("LoginAdm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Ainda não é cadastrado?</span></p></body></html>"))
        self.texto_erro.setHtml(_translate("LoginAdm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.texto_usuario.setHtml(_translate("LoginAdm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Usuário</span></p></body></html>"))
        self.texto_senha.setHtml(_translate("LoginAdm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Senha</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginAdm = QtWidgets.QWidget()
    ui = Ui_LoginAdm()
    ui.setupUi(LoginAdm)
    LoginAdm.show()
    sys.exit(app.exec_())
