# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_cadastroCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 421, 671))
        self.frame.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bt_salvarloginCliente = QtWidgets.QPushButton(self.frame)
        self.bt_salvarloginCliente.setEnabled(True)
        self.bt_salvarloginCliente.setGeometry(QtCore.QRect(100, 600, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_salvarloginCliente.setFont(font)
        self.bt_salvarloginCliente.setStyleSheet("QPushButton{\n"
"    background-color: rgba(221, 33, 33, 0.99);\n"
"    border-radius: 12px;\n"
"    color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 206, 137);\n"
"    border-radius: 12px;\n"
"    color: rgb(100, 76, 47);\n"
"}\n"
"")
        self.bt_salvarloginCliente.setObjectName("bt_salvarloginCliente")
        self.tck = QtWidgets.QLabel(self.frame)
        self.tck.setGeometry(QtCore.QRect(20, 10, 51, 31))
        self.tck.setStyleSheet("")
        self.tck.setText("")
        self.tck.setPixmap(QtGui.QPixmap("../imgs/tickets.png"))
        self.tck.setScaledContents(True)
        self.tck.setObjectName("tck")
        self.texto_infoCliente = QtWidgets.QTextEdit(self.frame)
        self.texto_infoCliente.setGeometry(QtCore.QRect(20, 70, 411, 31))
        self.texto_infoCliente.setStyleSheet("border: none;")
        self.texto_infoCliente.setObjectName("texto_infoCliente")
        self.texto_erro2 = QtWidgets.QTextEdit(self.frame)
        self.texto_erro2.setGeometry(QtCore.QRect(70, 560, 291, 31))
        self.texto_erro2.setStyleSheet("border: none;")
        self.texto_erro2.setObjectName("texto_erro2")
        self.texto_erro = QtWidgets.QTextEdit(self.frame)
        self.texto_erro.setGeometry(QtCore.QRect(170, 350, 104, 31))
        self.texto_erro.setStyleSheet("border: none;")
        self.texto_erro.setObjectName("texto_erro")
        self.box_insertUsuario = QtWidgets.QLineEdit(self.frame)
        self.box_insertUsuario.setGeometry(QtCore.QRect(20, 130, 371, 31))
        self.box_insertUsuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"border: none;")
        self.box_insertUsuario.setObjectName("box_insertUsuario")
        self.texto_usuarioCliente = QtWidgets.QTextEdit(self.frame)
        self.texto_usuarioCliente.setGeometry(QtCore.QRect(20, 100, 151, 31))
        self.texto_usuarioCliente.setStyleSheet("border: none;")
        self.texto_usuarioCliente.setObjectName("texto_usuarioCliente")
        self.texto_cpfCliente = QtWidgets.QTextEdit(self.frame)
        self.texto_cpfCliente.setGeometry(QtCore.QRect(20, 330, 131, 51))
        self.texto_cpfCliente.setStyleSheet("border: none;")
        self.texto_cpfCliente.setObjectName("texto_cpfCliente")
        self.texto_topo = QtWidgets.QTextEdit(self.frame)
        self.texto_topo.setGeometry(QtCore.QRect(90, 10, 151, 41))
        self.texto_topo.setStyleSheet("border: none;\n"
"color: rgba(221, 33, 33, 0.99);")
        self.texto_topo.setObjectName("texto_topo")
        self.box_insertEmail = QtWidgets.QLineEdit(self.frame)
        self.box_insertEmail.setGeometry(QtCore.QRect(20, 200, 371, 31))
        self.box_insertEmail.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"border: none;")
        self.box_insertEmail.setObjectName("box_insertEmail")
        self.box_insertTelefone = QtWidgets.QLineEdit(self.frame)
        self.box_insertTelefone.setGeometry(QtCore.QRect(20, 280, 371, 31))
        self.box_insertTelefone.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"border: none;")
        self.box_insertTelefone.setObjectName("box_insertTelefone")
        self.box_insertSenha = QtWidgets.QLineEdit(self.frame)
        self.box_insertSenha.setGeometry(QtCore.QRect(20, 360, 371, 31))
        self.box_insertSenha.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"border: none;")
        self.box_insertSenha.setObjectName("box_insertSenha")
        self.texto_emailCliente = QtWidgets.QTextEdit(self.frame)
        self.texto_emailCliente.setGeometry(QtCore.QRect(20, 170, 151, 31))
        self.texto_emailCliente.setStyleSheet("border: none;")
        self.texto_emailCliente.setObjectName("texto_emailCliente")
        self.texto_senhaCliente = QtWidgets.QTextEdit(self.frame)
        self.texto_senhaCliente.setGeometry(QtCore.QRect(20, 410, 201, 31))
        self.texto_senhaCliente.setStyleSheet("border: none;")
        self.texto_senhaCliente.setObjectName("texto_senhaCliente")
        self.texto_telefoneCliente = QtWidgets.QTextEdit(self.frame)
        self.texto_telefoneCliente.setGeometry(QtCore.QRect(20, 250, 104, 31))
        self.texto_telefoneCliente.setStyleSheet("border: none;")
        self.texto_telefoneCliente.setObjectName("texto_telefoneCliente")
        self.box_confirmaSenha = QtWidgets.QLineEdit(self.frame)
        self.box_confirmaSenha.setGeometry(QtCore.QRect(20, 440, 371, 31))
        self.box_confirmaSenha.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"border: none;")
        self.box_confirmaSenha.setObjectName("box_confirmaSenha")
        self.texto_confirmaSenhaCliente = QtWidgets.QTextEdit(self.frame)
        self.texto_confirmaSenhaCliente.setGeometry(QtCore.QRect(20, 490, 201, 31))
        self.texto_confirmaSenhaCliente.setStyleSheet("border: none;")
        self.texto_confirmaSenhaCliente.setObjectName("texto_confirmaSenhaCliente")
        self.box_confirmaSenha_2 = QtWidgets.QLineEdit(self.frame)
        self.box_confirmaSenha_2.setGeometry(QtCore.QRect(20, 520, 371, 31))
        self.box_confirmaSenha_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"border: none;")
        self.box_confirmaSenha_2.setObjectName("box_confirmaSenha_2")
        self.bt_voltar = QtWidgets.QPushButton(self.frame)
        self.bt_voltar.setEnabled(True)
        self.bt_voltar.setGeometry(QtCore.QRect(380, 630, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_voltar.setFont(font)
        self.bt_voltar.setStyleSheet("QPushButton{\n"
"    background-color: rgba(221, 33, 33, 0.99);\n"
"    border-radius: 12px;\n"
"    color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 206, 137);\n"
"    border-radius: 12px;\n"
"    color: rgb(100, 76, 47);\n"
"}\n"
"")
        self.bt_voltar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../imgs/voltar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_voltar.setIcon(icon)
        self.bt_voltar.setIconSize(QtCore.QSize(25, 25))
        self.bt_voltar.setObjectName("bt_voltar")
        self.texto_infoCliente.raise_()
        self.texto_emailCliente.raise_()
        self.texto_cpfCliente.raise_()
        self.texto_usuarioCliente.raise_()
        self.texto_erro2.raise_()
        self.tck.raise_()
        self.bt_salvarloginCliente.raise_()
        self.texto_erro.raise_()
        self.box_insertUsuario.raise_()
        self.texto_topo.raise_()
        self.box_insertEmail.raise_()
        self.box_insertTelefone.raise_()
        self.box_insertSenha.raise_()
        self.texto_senhaCliente.raise_()
        self.texto_telefoneCliente.raise_()
        self.box_confirmaSenha.raise_()
        self.texto_confirmaSenhaCliente.raise_()
        self.box_confirmaSenha_2.raise_()
        self.bt_voltar.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cadastro Cliente"))
        self.bt_salvarloginCliente.setText(_translate("Form", "SALVAR"))
        self.texto_infoCliente.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Preencha os campos abaixo para realizar seu cadastro.</span></p></body></html>"))
        self.texto_erro2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.texto_erro.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.texto_usuarioCliente.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Nome de usuário</span></p></body></html>"))
        self.texto_cpfCliente.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">CPF</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt; font-weight:600;\"><br /></p></body></html>"))
        self.texto_topo.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Bilheteria Online</span></p></body></html>"))
        self.texto_emailCliente.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">E-mail</span></p></body></html>"))
        self.texto_senhaCliente.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Senha</span></p></body></html>"))
        self.texto_telefoneCliente.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Telefone</span></p></body></html>"))
        self.texto_confirmaSenhaCliente.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Confirmação de senha</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
